version: "3.8"
services:
  biopatternsg-postgres:
    # Usamos la imagen oficial de pgvector basada en Postgres 17 (Stable)
    image: pgvector/pgvector:pg17
    container_name: "biopatternsg-postgres"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      # ESTA ES LA SOLUCIÓN PARA EL ESQUEMA:
      - ./init-db:/docker-entrypoint-initdb.d/
    networks:
      - general-network
    # Healthcheck: Ayuda a Quarkus a saber si la DB ya está lista para aceptar conexiones
    healthcheck:
      # CORRECCIÓN DEL USUARIO: Usamos la variable para que no falle
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  general-network:
    external: true